base.url=player-api-tests-production.up.railway.app
base.protocol=https
base.port=443

endpoint.login=/api/tester/login
endpoint.create=/api/automationTask/create
endpoint.get.all=/api/automationTask/getAll
endpoint.get.one=/api/automationTask/getOne
endpoint.delete=/api/automationTask/deleteOne

auth.username=tester
auth.password=tester123
